CREATE TABLE public.todos (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone DEFAULT now(),
    title text NOT NULL,
    completed boolean DEFAULT false NOT NULL,
    description text
);